version: "3"
services:
  api:
    container_name: api
    build: 
        context: ./api
        dockerfile: dev.Dockerfile
    ports: 
      - "3000:3000"
    environment:
      - TOP_HEADLINES_API_BASEURI=https://newsapi.org/v2/top-headlines?country=us&apiKey=<API_KEY>
      - ARTICLE_IMAGE_MOCK_URI=https://images.placeholders.dev/?width=256&height=256
    volumes:
      - ./api:/usr/src/app
    command: > 
        bash -c "npm install && npm run start:dev"
  frontend:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    container_name: frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/usr/src/app
    command: > 
        bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"
